python generate_R_par.py ../../data/output/paul_freq_par/par10_frequency.csv ../../data/output/paul_R_par/par10.R
python generate_R_par.py ../../data/output/paul_freq_par/par11_frequency.csv ../../data/output/paul_R_par/par11.R
python generate_R_par.py ../../data/output/paul_freq_par/par12_frequency.csv ../../data/output/paul_R_par/par12.R
python generate_R_par.py ../../data/output/paul_freq_par/par13_frequency.csv ../../data/output/paul_R_par/par13.R
python generate_R_par.py ../../data/output/paul_freq_par/par14_frequency.csv ../../data/output/paul_R_par/par14.R
python generate_R_par.py ../../data/output/paul_freq_par/par1_frequency.csv ../../data/output/paul_R_par/par1.R
python generate_R_par.py ../../data/output/paul_freq_par/par2_frequency.csv ../../data/output/paul_R_par/par2.R
python generate_R_par.py ../../data/output/paul_freq_par/par3_frequency.csv ../../data/output/paul_R_par/par3.R
python generate_R_par.py ../../data/output/paul_freq_par/par4_frequency.csv ../../data/output/paul_R_par/par4.R
python generate_R_par.py ../../data/output/paul_freq_par/par5_frequency.csv ../../data/output/paul_R_par/par5.R
python generate_R_par.py ../../data/output/paul_freq_par/par6_frequency.csv ../../data/output/paul_R_par/par6.R
python generate_R_par.py ../../data/output/paul_freq_par/par7_frequency.csv ../../data/output/paul_R_par/par7.R
python generate_R_par.py ../../data/output/paul_freq_par/par8_frequency.csv ../../data/output/paul_R_par/par8.R
python generate_R_par.py ../../data/output/paul_freq_par/par9_frequency.csv ../../data/output/paul_R_par/par9.R
python generate_R_par.py ../../data/output/peter_freq_par/par1_frequency.csv ../../data/output/peter_R_par/par1.R
python generate_R_par.py ../../data/output/peter_freq_par/par2_frequency.csv ../../data/output/peter_R_par/par2.R
python generate_R_par.py ../../data/output/peter_freq_par/par3_frequency.csv ../../data/output/peter_R_par/par3.R
python generate_R_par.py ../../data/output/peter_freq_par/par4_frequency.csv ../../data/output/peter_R_par/par4.R
python generate_R_par.py ../../data/output/peter_freq_par/par5_frequency.csv ../../data/output/peter_R_par/par5.R
python generate_R_par.py ../../data/output/peter_freq_par/par6_frequency.csv ../../data/output/peter_R_par/par6.R
